# Site settings
title: Nicolas Coia | Business, Art, & Design
description: "Let us unravel complexities and strategize a technical future."
url: "http://www.coianac.github.io/"
author:
  name: "Nicolas Coia"
  email: "coia.nac@gmail.com"
  url: "https://coianac.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# Collections
collections:
  blog:
    output: true
  education
    output: true
  portfolio
    output: true
